[versions]
compose-compiler = "1.3.0"
compose-runtime = "1.2.1"

[libraries]
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose-runtime" }
